---
version: "3"

services:
  avro-tools:
    build:
      context: .
      args:
        AVRO_TOOLS_VERSION: "${AVRO_TOOLS_VERSION}"
      tags:
        - "ghcr.io/cbdq-io/avro-tools:${AVRO_TOOLS_VERSION}"
        - "ghcr.io/cbdq-io/avro-tools:latest"
        - "ghcr.io/cbdq-io/avro-tools:stable"
    container_name: docker
